apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-manager-pod
  namespace: neuvector
spec:
  template:
    spec:
      containers:
        - name: neuvector-manager-pod
          resources:
            request:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-controller-pod
  namespace: neuvector
spec:
  template:
    spec:
      containers:
        - name: neuvector-controller-pod
          resources:
            request:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: neuvector-enforcer-pod
  namespace: neuvector
spec:
  template:
    spec:
      containers:
        - name: neuvector-enforcer-pod
          resources:
            request:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-scanner-pod
  namespace: neuvector
spec:
  template:
    spec:
      containers:
        - name: neuvector-scanner-pod
          resources:
            request:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: neuvector-updater-pod
  namespace: neuvector
spec:
  jobTemplate:
    spec:
      containers:
        - name: neuvector-updater-pod
          resources:
            request:
              memory: "1024Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

