apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nvcomplianceprofiles.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NvComplianceProfile
    listKind: NvComplianceProfileList
    plural: nvcomplianceprofiles
    singular: nvcomplianceprofile
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              templates:
                properties:
                  disable_system:
                    type: boolean
                  entries:
                    items:
                      properties:
                        tags:
                          items:
                            type: string
                          type: array
                        test_number:
                          type: string
                      required:
                      - test_number
                      type: object
                    type: array
                required:
                - entries
                type: object
            type: object
        type: object
    served: true
    storage: true

