apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nvvulnerabilityprofiles.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NvVulnerabilityProfile
    listKind: NvVulnerabilityProfileList
    plural: nvvulnerabilityprofiles
    singular: nvvulnerabilityprofile
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              profile:
                properties:
                  entries:
                    items:
                      properties:
                        comment:
                          type: string
                        days:
                          type: integer
                        domains:
                          items:
                            type: string
                          type: array
                        images:
                          items:
                            type: string
                          type: array
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                required:
                - entries
                type: object
            required:
            - profile
            type: object
        type: object
    served: true
    storage: true
