apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-cert-upgrader
  namespace: neuvector
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-job-creation
  namespace: neuvector
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  - cronjobs/finalizers
  verbs:
  - update
  - patch
